//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//


package com.sample.jaxb.domain.booking;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AuditData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuditData">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RequestStatus">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="OK"/>
 *               &lt;enumeration value="WARNING"/>
 *               &lt;enumeration value="ERROR"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MessageList" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Message" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="MessageId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}MessageId"/>
 *                             &lt;element name="MessageDescription" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}MessageDescription"/>
 *                           &lt;/sequence>
 *                           &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="BookingInbound" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="BookingId" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuditData", propOrder = {
    "requestStatus",
    "messageList"
})
public class AuditData {

    @XmlElement(name = "RequestStatus", required = true)
    protected String requestStatus;
    @XmlElement(name = "MessageList")
    protected AuditData.MessageList messageList;
    @XmlAttribute(name = "BookingInbound", required = true)
    protected BigInteger bookingInbound;
    @XmlAttribute(name = "BookingId", required = true)
    protected BigInteger bookingId;

    /**
     * Gets the value of the requestStatus property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRequestStatus() {
        return requestStatus;
    }

    /**
     * Sets the value of the requestStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRequestStatus(String value) {
        this.requestStatus = value;
    }

    /**
     * Gets the value of the messageList property.
     * 
     * @return
     *     possible object is
     *     {@link AuditData.MessageList }
     *     
     */
    public AuditData.MessageList getMessageList() {
        return messageList;
    }

    /**
     * Sets the value of the messageList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AuditData.MessageList }
     *     
     */
    public void setMessageList(AuditData.MessageList value) {
        this.messageList = value;
    }

    /**
     * Gets the value of the bookingInbound property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBookingInbound() {
        return bookingInbound;
    }

    /**
     * Sets the value of the bookingInbound property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBookingInbound(BigInteger value) {
        this.bookingInbound = value;
    }

    /**
     * Gets the value of the bookingId property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBookingId() {
        return bookingId;
    }

    /**
     * Sets the value of the bookingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBookingId(BigInteger value) {
        this.bookingId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Message" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="MessageId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}MessageId"/>
     *                   &lt;element name="MessageDescription" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}MessageDescription"/>
     *                 &lt;/sequence>
     *                 &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "message"
    })
    public static class MessageList {

        @XmlElement(name = "Message", required = true)
        protected List<AuditData.MessageList.Message> message;

        /**
         * Gets the value of the message property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the message property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getMessage().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link AuditData.MessageList.Message }
         * 
         * 
         */
        public List<AuditData.MessageList.Message> getMessage() {
            if (message == null) {
                message = new ArrayList<AuditData.MessageList.Message>();
            }
            return this.message;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="MessageId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}MessageId"/>
         *         &lt;element name="MessageDescription" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}MessageDescription"/>
         *       &lt;/sequence>
         *       &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "messageId",
            "messageDescription"
        })
        public static class Message {

            @XmlElement(name = "MessageId", required = true)
            protected String messageId;
            @XmlElement(name = "MessageDescription", required = true)
            protected String messageDescription;
            @XmlAttribute(name = "NumIdent", required = true)
            protected BigInteger numIdent;

            /**
             * Gets the value of the messageId property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMessageId() {
                return messageId;
            }

            /**
             * Sets the value of the messageId property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMessageId(String value) {
                this.messageId = value;
            }

            /**
             * Gets the value of the messageDescription property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getMessageDescription() {
                return messageDescription;
            }

            /**
             * Sets the value of the messageDescription property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setMessageDescription(String value) {
                this.messageDescription = value;
            }

            /**
             * Gets the value of the numIdent property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getNumIdent() {
                return numIdent;
            }

            /**
             * Sets the value of the numIdent property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setNumIdent(BigInteger value) {
                this.numIdent = value;
            }

        }

    }

}
