//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//


package com.sample.jaxb.domain.booking;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}HeaderInf"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}Services" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "headerInf",
    "services"
})
@XmlRootElement(name = "BookingDetail")
public class BookingDetail {

    @XmlElement(name = "HeaderInf", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true)
    protected HeaderInf headerInf;
    @XmlElement(name = "Services", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization")
    protected Services services;

    /**
     * Gets the value of the headerInf property.
     * 
     * @return
     *     possible object is
     *     {@link HeaderInf }
     *     
     */
    public HeaderInf getHeaderInf() {
        return headerInf;
    }

    /**
     * Sets the value of the headerInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link HeaderInf }
     *     
     */
    public void setHeaderInf(HeaderInf value) {
        this.headerInf = value;
    }

    /**
     * Gets the value of the services property.
     * 
     * @return
     *     possible object is
     *     {@link Services }
     *     
     */
    public Services getServices() {
        return services;
    }

    /**
     * Sets the value of the services property.
     * 
     * @param value
     *     allowed object is
     *     {@link Services }
     *     
     */
    public void setServices(Services value) {
        this.services = value;
    }

}
