//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//


package com.sample.jaxb.domain.booking;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Booking">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="BookingCaseList">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="BookingCase" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="LifeCicleMomentType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}LifeCicleMomentType"/>
 *                                       &lt;element name="Petitioner" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Petitioner"/>
 *                                       &lt;sequence>
 *                                         &lt;element name="ServiceDetailList">
 *                                           &lt;complexType>
 *                                             &lt;complexContent>
 *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                 &lt;sequence>
 *                                                   &lt;element name="ServiceDetail" maxOccurs="unbounded">
 *                                                     &lt;complexType>
 *                                                       &lt;complexContent>
 *                                                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                                           &lt;sequence>
 *                                                             &lt;element name="ServiceId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceId"/>
 *                                                             &lt;element name="SubrequestType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}SubrequestType"/>
 *                                                             &lt;element name="Detail" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Detail"/>
 *                                                             &lt;element name="AlarmType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}AlarmType"/>
 *                                                             &lt;element name="ServiceType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceType"/>
 *                                                             &lt;element name="OMTrackerReason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerReason"/>
 *                                                             &lt;element name="OMTrackerSubreason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerSubreason"/>
 *                                                           &lt;/sequence>
 *                                                         &lt;/restriction>
 *                                                       &lt;/complexContent>
 *                                                     &lt;/complexType>
 *                                                   &lt;/element>
 *                                                 &lt;/sequence>
 *                                               &lt;/restriction>
 *                                             &lt;/complexContent>
 *                                           &lt;/complexType>
 *                                         &lt;/element>
 *                                       &lt;/sequence>
 *                                     &lt;/sequence>
 *                                     &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                                     &lt;attribute name="ActionType" use="required" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ActionType" />
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *                 &lt;attribute name="BookingInbound" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *                 &lt;attribute name="BookingId" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "booking"
})
@XmlRootElement(name = "BookingCaseRQ")
public class BookingCaseRQ {

    @XmlElement(name = "Booking", required = true)
    protected BookingCaseRQ.Booking booking;

    /**
     * Gets the value of the booking property.
     * 
     * @return
     *     possible object is
     *     {@link BookingCaseRQ.Booking }
     *     
     */
    public BookingCaseRQ.Booking getBooking() {
        return booking;
    }

    /**
     * Sets the value of the booking property.
     * 
     * @param value
     *     allowed object is
     *     {@link BookingCaseRQ.Booking }
     *     
     */
    public void setBooking(BookingCaseRQ.Booking value) {
        this.booking = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="BookingCaseList">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="BookingCase" maxOccurs="unbounded">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="LifeCicleMomentType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}LifeCicleMomentType"/>
     *                             &lt;element name="Petitioner" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Petitioner"/>
     *                             &lt;sequence>
     *                               &lt;element name="ServiceDetailList">
     *                                 &lt;complexType>
     *                                   &lt;complexContent>
     *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                       &lt;sequence>
     *                                         &lt;element name="ServiceDetail" maxOccurs="unbounded">
     *                                           &lt;complexType>
     *                                             &lt;complexContent>
     *                                               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                                 &lt;sequence>
     *                                                   &lt;element name="ServiceId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceId"/>
     *                                                   &lt;element name="SubrequestType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}SubrequestType"/>
     *                                                   &lt;element name="Detail" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Detail"/>
     *                                                   &lt;element name="AlarmType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}AlarmType"/>
     *                                                   &lt;element name="ServiceType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceType"/>
     *                                                   &lt;element name="OMTrackerReason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerReason"/>
     *                                                   &lt;element name="OMTrackerSubreason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerSubreason"/>
     *                                                 &lt;/sequence>
     *                                               &lt;/restriction>
     *                                             &lt;/complexContent>
     *                                           &lt;/complexType>
     *                                         &lt;/element>
     *                                       &lt;/sequence>
     *                                     &lt;/restriction>
     *                                   &lt;/complexContent>
     *                                 &lt;/complexType>
     *                               &lt;/element>
     *                             &lt;/sequence>
     *                           &lt;/sequence>
     *                           &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *                           &lt;attribute name="ActionType" use="required" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ActionType" />
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *       &lt;attribute name="BookingInbound" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *       &lt;attribute name="BookingId" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "bookingCaseList"
    })
    public static class Booking {

        @XmlElement(name = "BookingCaseList", required = true)
        protected BookingCaseRQ.Booking.BookingCaseList bookingCaseList;
        @XmlAttribute(name = "BookingInbound", required = true)
        protected BigInteger bookingInbound;
        @XmlAttribute(name = "BookingId", required = true)
        protected BigInteger bookingId;

        /**
         * Gets the value of the bookingCaseList property.
         * 
         * @return
         *     possible object is
         *     {@link BookingCaseRQ.Booking.BookingCaseList }
         *     
         */
        public BookingCaseRQ.Booking.BookingCaseList getBookingCaseList() {
            return bookingCaseList;
        }

        /**
         * Sets the value of the bookingCaseList property.
         * 
         * @param value
         *     allowed object is
         *     {@link BookingCaseRQ.Booking.BookingCaseList }
         *     
         */
        public void setBookingCaseList(BookingCaseRQ.Booking.BookingCaseList value) {
            this.bookingCaseList = value;
        }

        /**
         * Gets the value of the bookingInbound property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBookingInbound() {
            return bookingInbound;
        }

        /**
         * Sets the value of the bookingInbound property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBookingInbound(BigInteger value) {
            this.bookingInbound = value;
        }

        /**
         * Gets the value of the bookingId property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getBookingId() {
            return bookingId;
        }

        /**
         * Sets the value of the bookingId property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setBookingId(BigInteger value) {
            this.bookingId = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="BookingCase" maxOccurs="unbounded">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="LifeCicleMomentType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}LifeCicleMomentType"/>
         *                   &lt;element name="Petitioner" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Petitioner"/>
         *                   &lt;sequence>
         *                     &lt;element name="ServiceDetailList">
         *                       &lt;complexType>
         *                         &lt;complexContent>
         *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                             &lt;sequence>
         *                               &lt;element name="ServiceDetail" maxOccurs="unbounded">
         *                                 &lt;complexType>
         *                                   &lt;complexContent>
         *                                     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                                       &lt;sequence>
         *                                         &lt;element name="ServiceId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceId"/>
         *                                         &lt;element name="SubrequestType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}SubrequestType"/>
         *                                         &lt;element name="Detail" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Detail"/>
         *                                         &lt;element name="AlarmType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}AlarmType"/>
         *                                         &lt;element name="ServiceType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceType"/>
         *                                         &lt;element name="OMTrackerReason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerReason"/>
         *                                         &lt;element name="OMTrackerSubreason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerSubreason"/>
         *                                       &lt;/sequence>
         *                                     &lt;/restriction>
         *                                   &lt;/complexContent>
         *                                 &lt;/complexType>
         *                               &lt;/element>
         *                             &lt;/sequence>
         *                           &lt;/restriction>
         *                         &lt;/complexContent>
         *                       &lt;/complexType>
         *                     &lt;/element>
         *                   &lt;/sequence>
         *                 &lt;/sequence>
         *                 &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
         *                 &lt;attribute name="ActionType" use="required" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ActionType" />
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "bookingCase"
        })
        public static class BookingCaseList {

            @XmlElement(name = "BookingCase", required = true)
            protected List<BookingCaseRQ.Booking.BookingCaseList.BookingCase> bookingCase;

            /**
             * Gets the value of the bookingCase property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the bookingCase property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getBookingCase().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase }
             * 
             * 
             */
            public List<BookingCaseRQ.Booking.BookingCaseList.BookingCase> getBookingCase() {
                if (bookingCase == null) {
                    bookingCase = new ArrayList<BookingCaseRQ.Booking.BookingCaseList.BookingCase>();
                }
                return this.bookingCase;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="LifeCicleMomentType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}LifeCicleMomentType"/>
             *         &lt;element name="Petitioner" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Petitioner"/>
             *         &lt;sequence>
             *           &lt;element name="ServiceDetailList">
             *             &lt;complexType>
             *               &lt;complexContent>
             *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                   &lt;sequence>
             *                     &lt;element name="ServiceDetail" maxOccurs="unbounded">
             *                       &lt;complexType>
             *                         &lt;complexContent>
             *                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                             &lt;sequence>
             *                               &lt;element name="ServiceId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceId"/>
             *                               &lt;element name="SubrequestType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}SubrequestType"/>
             *                               &lt;element name="Detail" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Detail"/>
             *                               &lt;element name="AlarmType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}AlarmType"/>
             *                               &lt;element name="ServiceType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceType"/>
             *                               &lt;element name="OMTrackerReason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerReason"/>
             *                               &lt;element name="OMTrackerSubreason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerSubreason"/>
             *                             &lt;/sequence>
             *                           &lt;/restriction>
             *                         &lt;/complexContent>
             *                       &lt;/complexType>
             *                     &lt;/element>
             *                   &lt;/sequence>
             *                 &lt;/restriction>
             *               &lt;/complexContent>
             *             &lt;/complexType>
             *           &lt;/element>
             *         &lt;/sequence>
             *       &lt;/sequence>
             *       &lt;attribute name="NumIdent" use="required" type="{http://www.w3.org/2001/XMLSchema}integer" />
             *       &lt;attribute name="ActionType" use="required" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ActionType" />
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lifeCicleMomentType",
                "petitioner",
                "serviceDetailList"
            })
            public static class BookingCase {

                @XmlElement(name = "LifeCicleMomentType", required = true)
                @XmlSchemaType(name = "string")
                protected LifeCicleMomentType lifeCicleMomentType;
                @XmlElement(name = "Petitioner", required = true)
                protected String petitioner;
                @XmlElement(name = "ServiceDetailList", required = true)
                protected BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList serviceDetailList;
                @XmlAttribute(name = "NumIdent", required = true)
                protected BigInteger numIdent;
                @XmlAttribute(name = "ActionType", required = true)
                protected ActionType actionType;

                /**
                 * Gets the value of the lifeCicleMomentType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link LifeCicleMomentType }
                 *     
                 */
                public LifeCicleMomentType getLifeCicleMomentType() {
                    return lifeCicleMomentType;
                }

                /**
                 * Sets the value of the lifeCicleMomentType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link LifeCicleMomentType }
                 *     
                 */
                public void setLifeCicleMomentType(LifeCicleMomentType value) {
                    this.lifeCicleMomentType = value;
                }

                /**
                 * Gets the value of the petitioner property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getPetitioner() {
                    return petitioner;
                }

                /**
                 * Sets the value of the petitioner property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setPetitioner(String value) {
                    this.petitioner = value;
                }

                /**
                 * Gets the value of the serviceDetailList property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList }
                 *     
                 */
                public BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList getServiceDetailList() {
                    return serviceDetailList;
                }

                /**
                 * Sets the value of the serviceDetailList property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList }
                 *     
                 */
                public void setServiceDetailList(BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList value) {
                    this.serviceDetailList = value;
                }

                /**
                 * Gets the value of the numIdent property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getNumIdent() {
                    return numIdent;
                }

                /**
                 * Sets the value of the numIdent property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setNumIdent(BigInteger value) {
                    this.numIdent = value;
                }

                /**
                 * Gets the value of the actionType property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link ActionType }
                 *     
                 */
                public ActionType getActionType() {
                    return actionType;
                }

                /**
                 * Sets the value of the actionType property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link ActionType }
                 *     
                 */
                public void setActionType(ActionType value) {
                    this.actionType = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="ServiceDetail" maxOccurs="unbounded">
                 *           &lt;complexType>
                 *             &lt;complexContent>
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *                 &lt;sequence>
                 *                   &lt;element name="ServiceId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceId"/>
                 *                   &lt;element name="SubrequestType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}SubrequestType"/>
                 *                   &lt;element name="Detail" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Detail"/>
                 *                   &lt;element name="AlarmType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}AlarmType"/>
                 *                   &lt;element name="ServiceType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceType"/>
                 *                   &lt;element name="OMTrackerReason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerReason"/>
                 *                   &lt;element name="OMTrackerSubreason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerSubreason"/>
                 *                 &lt;/sequence>
                 *               &lt;/restriction>
                 *             &lt;/complexContent>
                 *           &lt;/complexType>
                 *         &lt;/element>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "serviceDetail"
                })
                public static class ServiceDetailList {

                    @XmlElement(name = "ServiceDetail", required = true)
                    protected List<BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail> serviceDetail;

                    /**
                     * Gets the value of the serviceDetail property.
                     * 
                     * <p>
                     * This accessor method returns a reference to the live list,
                     * not a snapshot. Therefore any modification you make to the
                     * returned list will be present inside the JAXB object.
                     * This is why there is not a <CODE>set</CODE> method for the serviceDetail property.
                     * 
                     * <p>
                     * For example, to add a new item, do as follows:
                     * <pre>
                     *    getServiceDetail().add(newItem);
                     * </pre>
                     * 
                     * 
                     * <p>
                     * Objects of the following type(s) are allowed in the list
                     * {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail }
                     * 
                     * 
                     */
                    public List<BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail> getServiceDetail() {
                        if (serviceDetail == null) {
                            serviceDetail = new ArrayList<BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail>();
                        }
                        return this.serviceDetail;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType>
                     *   &lt;complexContent>
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                     *       &lt;sequence>
                     *         &lt;element name="ServiceId" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceId"/>
                     *         &lt;element name="SubrequestType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}SubrequestType"/>
                     *         &lt;element name="Detail" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}Detail"/>
                     *         &lt;element name="AlarmType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}AlarmType"/>
                     *         &lt;element name="ServiceType" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}ServiceType"/>
                     *         &lt;element name="OMTrackerReason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerReason"/>
                     *         &lt;element name="OMTrackerSubreason" type="{http://hotelbeds.com/service/domain/booking/cs/categorization}OMTrackerSubreason"/>
                     *       &lt;/sequence>
                     *     &lt;/restriction>
                     *   &lt;/complexContent>
                     * &lt;/complexType>
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "serviceId",
                        "subrequestType",
                        "detail",
                        "alarmType",
                        "serviceType",
                        "omTrackerReason",
                        "omTrackerSubreason"
                    })
                    public static class ServiceDetail {

                        @XmlElement(name = "ServiceId", required = true)
                        protected String serviceId;
                        @XmlElement(name = "SubrequestType", required = true)
                        protected String subrequestType;
                        @XmlElement(name = "Detail", required = true)
                        protected String detail;
                        @XmlElement(name = "AlarmType", required = true)
                        @XmlSchemaType(name = "string")
                        protected AlarmType alarmType;
                        @XmlElement(name = "ServiceType", required = true)
                        @XmlSchemaType(name = "string")
                        protected ServiceType serviceType;
                        @XmlElement(name = "OMTrackerReason", required = true)
                        protected String omTrackerReason;
                        @XmlElement(name = "OMTrackerSubreason", required = true)
                        protected String omTrackerSubreason;

                        /**
                         * Gets the value of the serviceId property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getServiceId() {
                            return serviceId;
                        }

                        /**
                         * Sets the value of the serviceId property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setServiceId(String value) {
                            this.serviceId = value;
                        }

                        /**
                         * Gets the value of the subrequestType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getSubrequestType() {
                            return subrequestType;
                        }

                        /**
                         * Sets the value of the subrequestType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setSubrequestType(String value) {
                            this.subrequestType = value;
                        }

                        /**
                         * Gets the value of the detail property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getDetail() {
                            return detail;
                        }

                        /**
                         * Sets the value of the detail property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setDetail(String value) {
                            this.detail = value;
                        }

                        /**
                         * Gets the value of the alarmType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link AlarmType }
                         *     
                         */
                        public AlarmType getAlarmType() {
                            return alarmType;
                        }

                        /**
                         * Sets the value of the alarmType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link AlarmType }
                         *     
                         */
                        public void setAlarmType(AlarmType value) {
                            this.alarmType = value;
                        }

                        /**
                         * Gets the value of the serviceType property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link ServiceType }
                         *     
                         */
                        public ServiceType getServiceType() {
                            return serviceType;
                        }

                        /**
                         * Sets the value of the serviceType property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link ServiceType }
                         *     
                         */
                        public void setServiceType(ServiceType value) {
                            this.serviceType = value;
                        }

                        /**
                         * Gets the value of the omTrackerReason property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getOMTrackerReason() {
                            return omTrackerReason;
                        }

                        /**
                         * Sets the value of the omTrackerReason property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setOMTrackerReason(String value) {
                            this.omTrackerReason = value;
                        }

                        /**
                         * Gets the value of the omTrackerSubreason property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getOMTrackerSubreason() {
                            return omTrackerSubreason;
                        }

                        /**
                         * Sets the value of the omTrackerSubreason property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setOMTrackerSubreason(String value) {
                            this.omTrackerSubreason = value;
                        }

                    }

                }

            }

        }

    }

}
