//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//


package com.sample.jaxb.domain.booking;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}GempCodEmp"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}GttoSeqTtoo"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}NomCortoTtoo"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}BranchCode"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}BranchName"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}RefTtoo"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}FecDesde"/>
 *         &lt;element ref="{http://hotelbeds.com/service/domain/booking/cs/categorization}FintCodInterface"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "gempCodEmp",
    "gttoSeqTtoo",
    "nomCortoTtoo",
    "branchCode",
    "branchName",
    "refTtoo",
    "fecDesde",
    "fintCodInterface"
})
@XmlRootElement(name = "HeaderInf")
public class HeaderInf {

    @XmlElement(name = "GempCodEmp", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true)
    protected String gempCodEmp;
    @XmlElement(name = "GttoSeqTtoo", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true)
    protected BigInteger gttoSeqTtoo;
    @XmlElement(name = "NomCortoTtoo", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true)
    protected String nomCortoTtoo;
    @XmlElement(name = "BranchCode", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true, nillable = true)
    protected BigInteger branchCode;
    @XmlElement(name = "BranchName", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true, nillable = true)
    protected String branchName;
    @XmlElement(name = "RefTtoo", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true, nillable = true)
    protected String refTtoo;
    @XmlElement(name = "FecDesde", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true, nillable = true)
    protected XMLGregorianCalendar fecDesde;
    @XmlElement(name = "FintCodInterface", namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", required = true, nillable = true)
    protected String fintCodInterface;

    /**
     * Gets the value of the gempCodEmp property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGempCodEmp() {
        return gempCodEmp;
    }

    /**
     * Sets the value of the gempCodEmp property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGempCodEmp(String value) {
        this.gempCodEmp = value;
    }

    /**
     * Gets the value of the gttoSeqTtoo property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getGttoSeqTtoo() {
        return gttoSeqTtoo;
    }

    /**
     * Sets the value of the gttoSeqTtoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setGttoSeqTtoo(BigInteger value) {
        this.gttoSeqTtoo = value;
    }

    /**
     * Gets the value of the nomCortoTtoo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNomCortoTtoo() {
        return nomCortoTtoo;
    }

    /**
     * Sets the value of the nomCortoTtoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNomCortoTtoo(String value) {
        this.nomCortoTtoo = value;
    }

    /**
     * Gets the value of the branchCode property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getBranchCode() {
        return branchCode;
    }

    /**
     * Sets the value of the branchCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setBranchCode(BigInteger value) {
        this.branchCode = value;
    }

    /**
     * Gets the value of the branchName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBranchName() {
        return branchName;
    }

    /**
     * Sets the value of the branchName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBranchName(String value) {
        this.branchName = value;
    }

    /**
     * Gets the value of the refTtoo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRefTtoo() {
        return refTtoo;
    }

    /**
     * Sets the value of the refTtoo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRefTtoo(String value) {
        this.refTtoo = value;
    }

    /**
     * Gets the value of the fecDesde property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getFecDesde() {
        return fecDesde;
    }

    /**
     * Sets the value of the fecDesde property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setFecDesde(XMLGregorianCalendar value) {
        this.fecDesde = value;
    }

    /**
     * Gets the value of the fintCodInterface property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFintCodInterface() {
        return fintCodInterface;
    }

    /**
     * Sets the value of the fintCodInterface property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFintCodInterface(String value) {
        this.fintCodInterface = value;
    }

}
