//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//


package com.sample.jaxb.domain.booking;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LifeCicleMomentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="LifeCicleMomentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="Pre Arrival"/>
 *     &lt;enumeration value="On Spot"/>
 *     &lt;enumeration value="Post Travel"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "LifeCicleMomentType")
@XmlEnum
public enum LifeCicleMomentType {

    @XmlEnumValue("Pre Arrival")
    PRE_ARRIVAL("Pre Arrival"),
    @XmlEnumValue("On Spot")
    ON_SPOT("On Spot"),
    @XmlEnumValue("Post Travel")
    POST_TRAVEL("Post Travel");
    private final String value;

    LifeCicleMomentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static LifeCicleMomentType fromValue(String v) {
        for (LifeCicleMomentType c: LifeCicleMomentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
