//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//


package com.sample.jaxb.domain.booking;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.sample.jaxb.domain.bookincase package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _GempCodEmp_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "GempCodEmp");
    private final static QName _FintCodInterface_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "FintCodInterface");
    private final static QName _ServiceOrder_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "ServiceOrder");
    private final static QName _SupplierCode_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "SupplierCode");
    private final static QName _NomCortoTtoo_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "NomCortoTtoo");
    private final static QName _HotelCode_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "HotelCode");
    private final static QName _RefTtoo_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "RefTtoo");
    private final static QName _GttoSeqTtoo_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "GttoSeqTtoo");
    private final static QName _FecDesde_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "FecDesde");
    private final static QName _ServiceType_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "ServiceType");
    private final static QName _SupplierName_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "SupplierName");
    private final static QName _ServiceName_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "ServiceName");
    private final static QName _BranchCode_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "BranchCode");
    private final static QName _BranchName_QNAME = new QName("http://hotelbeds.com/service/domain/booking/cs/categorization", "BranchName");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.sample.jaxb.domain.bookincase
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link BookingCaseRQ }
     * 
     */
    public BookingCaseRQ createBookingCaseRQ() {
        return new BookingCaseRQ();
    }

    /**
     * Create an instance of {@link BookingDetailRQ }
     * 
     */
    public BookingDetailRQ createBookingDetailRQ() {
        return new BookingDetailRQ();
    }

    /**
     * Create an instance of {@link AuditData }
     * 
     */
    public AuditData createAuditData() {
        return new AuditData();
    }

    /**
     * Create an instance of {@link AuditData.MessageList }
     * 
     */
    public AuditData.MessageList createAuditDataMessageList() {
        return new AuditData.MessageList();
    }

    /**
     * Create an instance of {@link BookingCaseRQ.Booking }
     * 
     */
    public BookingCaseRQ.Booking createBookingCaseRQBooking() {
        return new BookingCaseRQ.Booking();
    }

    /**
     * Create an instance of {@link BookingCaseRQ.Booking.BookingCaseList }
     * 
     */
    public BookingCaseRQ.Booking.BookingCaseList createBookingCaseRQBookingBookingCaseList() {
        return new BookingCaseRQ.Booking.BookingCaseList();
    }

    /**
     * Create an instance of {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase }
     * 
     */
    public BookingCaseRQ.Booking.BookingCaseList.BookingCase createBookingCaseRQBookingBookingCaseListBookingCase() {
        return new BookingCaseRQ.Booking.BookingCaseList.BookingCase();
    }

    /**
     * Create an instance of {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList }
     * 
     */
    public BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList createBookingCaseRQBookingBookingCaseListBookingCaseServiceDetailList() {
        return new BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList();
    }

    /**
     * Create an instance of {@link BookingDetail }
     * 
     */
    public BookingDetail createBookingDetail() {
        return new BookingDetail();
    }

    /**
     * Create an instance of {@link HeaderInf }
     * 
     */
    public HeaderInf createHeaderInf() {
        return new HeaderInf();
    }

    /**
     * Create an instance of {@link Services }
     * 
     */
    public Services createServices() {
        return new Services();
    }

    /**
     * Create an instance of {@link ServiceInf }
     * 
     */
    public ServiceInf createServiceInf() {
        return new ServiceInf();
    }

    /**
     * Create an instance of {@link BookingCaseRS }
     * 
     */
    public BookingCaseRS createBookingCaseRS() {
        return new BookingCaseRS();
    }

    /**
     * Create an instance of {@link BookingDetailRQ.Booking }
     * 
     */
    public BookingDetailRQ.Booking createBookingDetailRQBooking() {
        return new BookingDetailRQ.Booking();
    }

    /**
     * Create an instance of {@link BookingDetailRS }
     * 
     */
    public BookingDetailRS createBookingDetailRS() {
        return new BookingDetailRS();
    }

    /**
     * Create an instance of {@link AuditData.MessageList.Message }
     * 
     */
    public AuditData.MessageList.Message createAuditDataMessageListMessage() {
        return new AuditData.MessageList.Message();
    }

    /**
     * Create an instance of {@link BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail }
     * 
     */
    public BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail createBookingCaseRQBookingBookingCaseListBookingCaseServiceDetailListServiceDetail() {
        return new BookingCaseRQ.Booking.BookingCaseList.BookingCase.ServiceDetailList.ServiceDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "GempCodEmp")
    public JAXBElement<String> createGempCodEmp(String value) {
        return new JAXBElement<String>(_GempCodEmp_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "FintCodInterface")
    public JAXBElement<String> createFintCodInterface(String value) {
        return new JAXBElement<String>(_FintCodInterface_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "ServiceOrder")
    public JAXBElement<BigInteger> createServiceOrder(BigInteger value) {
        return new JAXBElement<BigInteger>(_ServiceOrder_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "SupplierCode")
    public JAXBElement<BigInteger> createSupplierCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_SupplierCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "NomCortoTtoo")
    public JAXBElement<String> createNomCortoTtoo(String value) {
        return new JAXBElement<String>(_NomCortoTtoo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "HotelCode")
    public JAXBElement<BigInteger> createHotelCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_HotelCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "RefTtoo")
    public JAXBElement<String> createRefTtoo(String value) {
        return new JAXBElement<String>(_RefTtoo_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "GttoSeqTtoo")
    public JAXBElement<BigInteger> createGttoSeqTtoo(BigInteger value) {
        return new JAXBElement<BigInteger>(_GttoSeqTtoo_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "FecDesde")
    public JAXBElement<XMLGregorianCalendar> createFecDesde(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_FecDesde_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "ServiceType")
    public JAXBElement<String> createServiceType(String value) {
        return new JAXBElement<String>(_ServiceType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "SupplierName")
    public JAXBElement<String> createSupplierName(String value) {
        return new JAXBElement<String>(_SupplierName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "ServiceName")
    public JAXBElement<String> createServiceName(String value) {
        return new JAXBElement<String>(_ServiceName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "BranchCode")
    public JAXBElement<BigInteger> createBranchCode(BigInteger value) {
        return new JAXBElement<BigInteger>(_BranchCode_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization", name = "BranchName")
    public JAXBElement<String> createBranchName(String value) {
        return new JAXBElement<String>(_BranchName_QNAME, String.class, null, value);
    }

}
