//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.10 at 02:38:20 PM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://hotelbeds.com/service/domain/booking/cs/categorization")
package com.sample.jaxb.domain.booking;
