//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.14 at 10:25:32 AM CET 
//


package com.sample.jaxb.domain.purchase;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OrderDetail" type="{http://NamespaceTest.com/OrderTypes}OrderType"/>
 *         &lt;element name="PaymentMethod" type="{http://NamespaceTest.com/CommonTypes}PaymentMethodType"/>
 *         &lt;element ref="{http://NamespaceTest.com/Purchase}CustomerDetails"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "orderDetail",
    "paymentMethod",
    "customerDetails"
})
@XmlRootElement(name = "Purchase", namespace = "http://NamespaceTest.com/Purchase")
public class Purchase {

    @XmlElement(name = "OrderDetail", namespace = "http://NamespaceTest.com/Purchase", required = true)
    protected OrderType orderDetail;
    @XmlElement(name = "PaymentMethod", namespace = "http://NamespaceTest.com/Purchase", required = true)
    @XmlSchemaType(name = "string")
    protected PaymentMethodType paymentMethod;
    @XmlElement(name = "CustomerDetails", namespace = "http://NamespaceTest.com/Purchase", required = true)
    protected CustomerType customerDetails;

    /**
     * Gets the value of the orderDetail property.
     * 
     * @return
     *     possible object is
     *     {@link OrderType }
     *     
     */
    public OrderType getOrderDetail() {
        return orderDetail;
    }

    /**
     * Sets the value of the orderDetail property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrderType }
     *     
     */
    public void setOrderDetail(OrderType value) {
        this.orderDetail = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link PaymentMethodType }
     *     
     */
    public PaymentMethodType getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link PaymentMethodType }
     *     
     */
    public void setPaymentMethod(PaymentMethodType value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the customerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomerDetails() {
        return customerDetails;
    }

    /**
     * Sets the value of the customerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setCustomerDetails(CustomerType value) {
        this.customerDetails = value;
    }

}
